### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cbarrick** [m19c/gulp-run#9]
Experimental Windows support has landed in master. The only difference is that gulp-run on Windows calls `cmd.exe /c <command>` instead of `sh -c <command>`.

Can a Windows user run the tests and report back here? The help would be very much appreciated!

**Comment by TheDutchCoder** [comment]
Doesn't work for commands like "mkdir -p somedir", which will actually create two directories, instead of checking if "somedir" exists.

**Comment by cbarrick** [comment]
There is no `-p` option on [Windows's `mkdir`](https://technet.microsoft.com/en-us/library/bb490930.aspx).

If you're trying to use a POSIX compliant `mkdir`, try giving it the full path to the binary, or maybe run gulp from a Cygwin shell (in which case there's no need to use the windows option in gulp-run).

**Comment by TheDutchCoder** [comment]
But... Why is it trying to run Windows native commands?

Isn't the whole point of this plugin to pipe commands to the shell? I'm using bash and running "mkdir -p somedir" works fine in the CLI.

If that's not the point of this plugin, would you then know what other plugin does support this?

**Comment by cbarrick** [comment]
By default, gulp-run uses cmd.exe on Windows instead of bash. That way it can work for all Windows users without depending on bash. You can use the full path to the mkdir binary you want to use, or change your PATH environment variable so the posix mkdir takes priority over the Windows mkdir. I think PowerShell's mkdir supports `-p`, so you can try the powershell option too.

**Comment by cbarrick** [comment]
or try `bash -c mkdir -p somedir` as the command

**Comment by TheDutchCoder** [comment]
That last command doesn't work.

I'll just resort to piping the stream to a gulp.dest(). It's not pretty but it does the job as it automatically takes care of creating a folder if it's not present.
